### PR TITLE
feature: ZENKO-1421 update dependencies

### PR DESCRIPTION
**Pull request by rahulreddy**

### CODE REVIEW

**Review by philipyoo — APPROVED** [review]

**Comment by rahulreddy** [comment]
@bert-e approve

**Comment by rahulreddy** [comment]
@bert-e status

**Comment by rahulreddy** [comment]
@bert-e help

**Comment by rahulreddy** [comment]
@bert-e bypass_peer_approval

**Comment by rahulreddy** [comment]
@bert-e bypass_build_status

**Pull request merged**
