### PR TITLE
Improvement/gdl 5 revert node 16 upgrade

### PR DESCRIPTION
**Pull request by naren-rajendran**
Reverting node 16 upgrade.

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]

**Review by nicolas2bert — APPROVED** [review]

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e force_reset

**Pull request merged**
